version: "3.7"

services:

  app_proxy:
    environment:
      APP_HOST: fixedcoin_fixedcoin_node_1
      APP_PORT: 80

  fixedcoin_node:
    image: nginx:alpine
    init: true
    volumes:
      - ${APP_DATA_DIR}/data:/data
      - ./www:/usr/share/nginx/html:ro
