version: "3.8"

services:
  app_proxy:
    image: getumbrel/app-proxy:v0.1.0
    container_name: fixedcoin_app_proxy
    restart: on-failure
    ports:
      - "${APP_FIXEDCOIN_PORT:-8080}:8080"
    environment:
      APP_HOST: fixedcoin_node
      APP_PORT: 8080
      PROXY_AUTH_ADD: "false"
    depends_on:
      - fixedcoin_node

  fixedcoin_node:
    build: .
    container_name: fixedcoin_node
    restart: on-failure
    ports:
      - "24768:24768"
      - "24761:24761"
    volumes:
      - ${APP_DATA_DIR}/data:/data
    environment:
      - RPC_USER=umbrel
      - RPC_PASSWORD=changeme
    networks:
      fixedcoin_network:
        ipv4_address: 172.16.0.10

networks:
  fixedcoin_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.0.0/24
